import './globals.css';
import type { Metadata } from 'next';
import Topbar from './shared/Topbar';
import LeftSidebar from './shared/LeftSidebar';

export const metadata: Metadata = {
  title: 'SMS App',
  description: 'Generated by SMS app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <main className=''>
          <Topbar />
          <LeftSidebar />
          <section className='flex justify-center mx-auto w-4xl pt-[100px] h-screen'>
            <div className='w-full max-w-4xl'> {children}</div>
          </section>
        </main>
      </body>
    </html>
  );
}
